[package]
name = "andro"
version = "1.2.1"
edition = "2024"

[dependencies]
serde = { version = "1.0", features = ["derive"] }
clap = { version = "4.1.0", features= ["derive"] }
bincode = "1.3"
ctrlc = "3.5"

bridge_core = { path = "../bridge_core" }
